### ISSUE TITLE
When zooming in I can not see the text for this example

### ISSUE THREAD

**Issue by clapierre** [w3c/graphics-aria#3] opened 2018-03-06 14:41 UTC
![screen shot 2018-03-06 at 6 37 21 am](https://user-images.githubusercontent.com/7736749/37038187-fae19156-2108-11e8-98a8-4dd23d5d47fb.png)

This is on a Mac with Safari
However this looks fine zoomed in with FireFox and Chrome on a Mac.

**Comment by AmeliaBR** [comment] 2018-03-18 00:38
Hmm, I assume the problem is with Safari's text-only zoom. I'll take a look, and see if there's something I can fix in the markup, or if it is really a Safari bug.

**Comment by AmeliaBR** [comment] 2018-03-20 16:39
Update: @alastc did some testing and determined that the problem was in regular browser pixel-based zoom, not the text-only zoom, so our conclusion is that this is a Safari bug. He filed: https://bugs.webkit.org/show_bug.cgi?id=183780

**Comment by michael-n-cooper** [comment] 2018-05-29 17:04
Assuming this issue is not something that will result in edits to our spec, so closing.

**Closed as completed by michael-n-cooper** 2018-05-29 17:04 UTC
